import csv

# Array of insurance questions
insurance_questions = [
    "What does my policy include?",
    "How can I file a claim?",
    "Is there coverage if I drive another person's car?",
    "Can I use my vehicle in a foreign country?",
    "What are the steps if my car is stolen?",
    "How should I handle a damaged windscreen?",
    "Is my electric vehicle's battery covered?",
    "What happens if I put the wrong fuel in my car?",
    "How do I update my personal information?",
    "What is my deductible?",
    "Can I add a secondary driver to my policy?",
    "How do I terminate my policy?",
    "What is a no-claims bonus?",
    "Does my policy cover rental cars?",
    "What should I do if I need to file a complaint?",
    "Can I pay my insurance premium in installments?",
    "What is an insurance premium?",
    "Are car modifications covered by my policy?",
    "Am I protected against natural disasters?",
    "What steps should I take if I'm in an accident?",
    "Does my policy cover vandalism?",
    "What does comprehensive coverage entail?",
    "How do I renew my insurance policy?",
    "What happens if my car is declared a total loss?",
    "Is roadside assistance part of my policy?",
    "What liability coverage is available when driving another car?",
    "What conditions must be met for coverage when driving another car?",
    "Under what circumstances might the insurer seek repayment for out-of-policy payments?",
    "What are the exclusions for liability coverage?",
    "Are legal fees for speeding offences covered by the policy?",
    "Does Motor Legal Cover apply if I'm driving another car?",
    "What exclusions are there when driving another car?",
    "How is coverage for automated cars in Great Britain handled?",
    "What requirements must be met for automated car coverage to apply?",
    "What actions can lead to exclusion from automated car coverage?",
    "What fire and theft coverage does the policy provide?",
    "Are child car seats covered in case of fire or theft?",
    "What is the coverage for in-car entertainment systems installed in the car?",
    "Is there coverage for removable electronic devices in case of fire or theft?",
    "What conditions must be met to claim for stolen car keys?",
    "Is a courtesy car provided while my car is being repaired?",
    "What kind of car is provided as a courtesy car?",
    "What actions might result in denial of a courtesy car?",
    "What does the policy cover for accidental damage to my car?",
    "Is misfuelling covered by the policy?",
    "What coverage is provided for lost or damaged car keys?",
    "Is windscreen damage included in the policy?",
    "What personal benefits are included in the policy?",
    "Is there coverage for accidents involving uninsured drivers?",
    "How does the New Car Replacement feature work?",
    "What does Motor Legal Cover include?",
    "Under what conditions is Motor Legal Cover applicable?",
    "What is the extent of Motor Legal Cover included with the policy?",
    "Who is protected under Motor Legal Cover?",
    "What types of claims are assisted by Motor Legal Cover?",
    "What are examples of uninsured losses in road traffic accidents covered by Motor Legal Cover?",
    "When does Motor Legal Cover apply if you're prosecuted for a driving offence?",
    "What motor contract disputes are covered by Motor Legal Cover?",
    "Under what circumstances can Motor Legal Cover be used in a road traffic accident?",
    "What is the maximum amount Motor Legal Cover provides?",
    "What is the purpose of the motor legal helpline?",
    "In what situations are you not covered by Motor Legal Cover?",
    "Which driving offences are not covered by Motor Legal Cover?",
    "When does Motor Legal Cover exclude coverage for motoring offences?",
    "What does 'reasonable chance of succeeding' mean in Motor Legal Cover?",
    "What role does the appointed representative play in Motor Legal Cover?",
    "Can you choose your own appointed representative under Motor Legal Cover?",
    "What happens if there are conflicting opinions about the success of your claim in Motor Legal Cover?",
    "How are costs assessed and recovered under Motor Legal Cover?",
    "What responsibilities does the policyholder have regarding Motor Legal Cover?",
    "What actions can jeopardize your position in relation to Motor Legal Cover?",
    "Why is it important to settle or end your claim under Motor Legal Cover?",
    "What happens if you refuse a settlement offer under Motor Legal Cover?",
    "How are costs verified and recovered under Motor Legal Cover?",
    "What are the limitations on using your hire car under Guaranteed Hire Car Plus?",
    "What types of damage caused by pressure waves are excluded?",
    "Is damage from pressure waves created by supersonic aircraft covered by the policy?",
    "Does the policy cover damage caused by automated cars driving themselves?",
    "Under what conditions is damage caused by automated cars not covered?",
    "What is required for coverage of damage caused by automated cars?",
    "Does the policy cover damage from computer system failures?",
    "What cyber events are excluded from the policy?",
    "What are the requirements for providing accurate information to the insurer?",
    "What are your responsibilities regarding the roadworthiness of your car?",
    "What steps should you take to protect your car and its contents?",
    "When can the insurer inspect your car?",
    "What are considered modifications to your car according to the policy?",
    "What should you do if you plan to modify your car?",
    "What happens if you don't provide correct information about car modifications?",
    "What is the policy on fraud?",
    "What actions can the insurer take if fraud is detected?",
    "Does the policy cover losses already insured by another policy?",
    "Who is insured under the policy?",
    "What are the conditions for car sharing coverage?",
    "What actions can the insurer take on your behalf regarding claims?",
    "What changes must you inform the insurer about before your coverage starts?",
    "What changes must you inform the insurer about after your coverage begins?",
    "What happens if you don't inform the insurer about changes?",
    "How do you pay your premium?",
    "What happens if the insurer can't collect your payment?",
    "What are the conditions for canceling the policy and removing optional coverage?",
    "How are refunds handled if you cancel the policy?",
    "How does the No Claim Discount (NCD) work?",
    "What happens if you file a claim on your policy?",
    "What laws govern the contract according to the policy?",
    "What is the process for filing a complaint?",
    "How can you contact the insurer to file a complaint?",
    "What communication can you expect during the complaint process?",
    "What if your complaint isn't resolved within 8 weeks?",
    "What is the Motor Insurance Database (MID)?",
    "What steps should you follow if you're in an accident?",
    "What contact information is available for claims and support?",
    "Who underwrites Churchill insurance policies?"
]

# Writing to a CSV file
with open('insurance_questions.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    for question in insurance_questions:
        writer.writerow([question])

print("CSV file created successfully!")